project:
  type: book

book:
  title: "Data cleaning for social scientists"
  author: "Felix Lennert"
  date: "2022-11-23"
  chapters:
    - index.qmd
    - projects.qmd
    - readr.qmd
    - tidy-data.qmd
    - dplyr.qmd
    - forcats.qmd
    - lubridate.qmd
    - ggplot2.qmd
    - exercises.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

