project:
  type: book

book:
  title: "Data cleaning for social scientists"
  author: "Felix Lennert"
  date: "last update: `r lubridate::today()`"
  chapters:
    - index.qmd
    - projects_readr.qmd
    - tidy-data.qmd
    - dplyr.qmd
    - forcats_lubridate.qmd
    - ggplot2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

